name: Setup Environment
description: Set up Node.js, Rust and dependencies

inputs:
  node-version:
    description: 'The Node.js version to use'
    required: true
    default: lts/*

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    - uses: swatinem/rust-cache@v2

    - run: corepack enable && pnpm install
      shell: bash
