// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Config = { "version": "V0", source: string | null, target: string | null, pattern: string | null, };