name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          use-ubuntu: ${{ matrix.platform == 'ubuntu-20.04' }}
      
      - name: Set version in tauri.conf.json
        uses: actions/github-script@v7
        env:
          TAG_NAME: ${{ github.ref_name }}
        with:
          script: |
            const [fs, path] = [require('fs'), require('path')];
            const version = process.env.TAG_NAME.replace(/^v/, '');
            const configPath = path.join(process.env.GITHUB_WORKSPACE, 'src-tauri', 'tauri.conf.json');
            const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
            config.package.version = version;
            fs.writeFileSync(configPath, JSON.stringify(config));

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: 'move v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false
